name: "AirSend"
description: "AirSend Web Service (local connection, no internet, no cloud)"
version: "1.3"
slug: "airsend"
url: https://github.com/devmel/hass_airsend-addon
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
startup: services
init: false
ports:
  33863/tcp: null
ports_description:
  33863/tcp: AirSendWebService communication
options:
  auto_include: true
schema:
  auto_include: bool
